#pragma once

#include "problem_001_sum_of_naturals_divisible_by_3_or_5.h"
#include "problem_002_greatest_common_divisor.h"
#include "problem_003_least_common_multiple.h"
#include "problem_004_largest_prime_smaller_than_given_number.h"
#include "problem_005_sexy_prime_pairs.h"
#include "problem_006_abundant_numbers.h"
#include "problem_007_amicable_numbers.h"
#include "problem_008_armstrong_numbers.h"
#include "problem_009_prime_factors.h"
#include "problem_010_gray_code.h"
#include "problem_011_converting_numerical_values_to_roman.h"
#include "problem_012_largest_collatz_sequence.h"
#include "problem_013_computing_the_value_of_pi.h"
#include "problem_014_validating_isbns.h"
