#include "chapter_08_design_patterns/problem_072_computing_order_price_with_discounts.h"

#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include <sstream>  // ostringstream


TEST(problem_72_main, DISABLED_output) {
    std::ostringstream oss{};
    problem_72_main(oss);
    EXPECT_THAT(oss.str(), ::testing::HasSubstr(
        "Store:\n"
        "    store[\n"
        "        article(\n"
        "            id : 0,\n"
        "            price : 1,\n"
        "            discounts : []\n"
        "        ),\n"
        "        article(\n"
        "            id : 1,\n"
        "            price : 2,\n"
        "            discounts : [\n"
        "                article_fixed_discount(percentage : 0.05)\n"
        "            ]\n"
        "        ),\n"
        "        article(\n"
        "            id : 2,\n"
        "            price : 4,\n"
        "            discounts : []\n"
        "        ),\n"
        "        article(\n"
        "            id : 3,\n"
        "            price : 8,\n"
        "            discounts : []\n"
        "        ),\n"
        "        article(\n"
        "            id : 5,\n"
        "            price : 16,\n"
        "            discounts : []\n"
        "        )\n"
        "    ]\n"
        "\n"
        "Order 1:\n"
        "    order(\n"
        "        id : 0,\n"
        "        order_lines : [\n"
        "            order_line(\n"
        "                article(\n"
        "                    id : 0,\n"
        "                    price : 1,\n"
        "                    discounts : []\n"
        "                ),\n"
        "                quantity : 6,\n"
        "                discounts : [\n"
        "                    order_line_volume_discount(percentage : 0.2, minimum_article_quantity : 3)\n"
        "                ]\n"
        "            ),\n"
        "            order_line(\n"
        "                article(\n"
        "                    id : 1,\n"
        "                    price : 2,\n"
        "                    discounts : [\n"
        "                        article_fixed_discount(percentage : 0.05)\n"
        "                    ]\n"
        "                ),\n"
        "                quantity : 2,\n"
        "                discounts : []\n"
        "            ),\n"
        "            order_line(\n"
        "                article(\n"
        "                    id : 5,\n"
        "                    price : 16,\n"
        "                    discounts : []\n"
        "                ),\n"
        "                quantity : 2,\n"
        "                discounts : [\n"
        "                    order_line_price_discount(percentage : 0.1, minimum_total_article_price : 20)\n"
        "                ]\n"
        "            )\n"
        "        ],\n"
        "        customer(\n"
        "            id : 0,\n"
        "            discounts : []\n"
        "        ),\n"
        "        discounts : []\n"
        "    )\n"
        "\n"
        "Order 2:\n"
        "    order(\n"
        "        id : 1,\n"
        "        order_lines : [\n"
        "            order_line(\n"
        "                article(\n"
        "                    id : 2,\n"
        "                    price : 4,\n"
        "                    discounts : []\n"
        "                ),\n"
        "                quantity : 10,\n"
        "                discounts : [\n"
        "                    order_line_price_discount(percentage : 0.1, minimum_total_article_price : 20)\n"
        "                ]\n"
        "            ),\n"
        "            order_line(\n"
        "                article(\n"
        "                    id : 3,\n"
        "                    price : 8,\n"
        "                    discounts : []\n"
        "                ),\n"
        "                quantity : 10,\n"
        "                discounts : [\n"
        "                    order_line_price_discount(percentage : 0.1, minimum_total_article_price : 20)\n"
        "                ]\n"
        "            )\n"
        "        ],\n"
        "        customer(\n"
        "            id : 1,\n"
        "            discounts : [\n"
        "                article_fixed_discount(percentage : 0.05)\n"
        "            ]\n"
        "        ),\n"
        "        discounts : [\n"
        "            order_price_discount(percentage : 0.03, minimum_total_order_price : 100)\n"
        "        ]\n"
        "    )\n"
        "\n"
        "Cumulative price for order 1: 37.4\n"
        "Cumulative price for order 2: 99.36\n"
        "Non cumulative price for order 1: 37.4\n"
        "Non cumulative price for order 2: 108\n"
    ));
}
